-- Strongly-typed runtime settings for Solo Ban/Pick rating control.
-- Safe to run on local MySQL 8+ before backend compile/test verification.

START TRANSACTION;

CREATE TABLE IF NOT EXISTS ban_pick_rating_config (
    id BIGINT NOT NULL,
    initial_rating INT NOT NULL DEFAULT 1000,
    base_win_delta INT NOT NULL DEFAULT 30,
    base_loss_delta INT NOT NULL DEFAULT -20,
    min_rating INT NOT NULL DEFAULT 0,
    macro_enabled TINYINT(1) NOT NULL DEFAULT 1,
    macro_active_window_days INT NOT NULL DEFAULT 30,
    macro_balance_rating INT NOT NULL DEFAULT 1500,
    macro_active_top_percent INT NOT NULL DEFAULT 50,
    macro_rating_step INT NOT NULL DEFAULT 10,
    macro_win_adjustment_per_step DECIMAL(8,4) NOT NULL DEFAULT 0.0200,
    macro_min_win_delta INT NOT NULL DEFAULT 20,
    macro_minimum_active_players INT NOT NULL DEFAULT 4,
    gap_enabled TINYINT(1) NOT NULL DEFAULT 1,
    gap_rating_diff_step INT NOT NULL DEFAULT 10,
    gap_modifier_per_step DECIMAL(8,4) NOT NULL DEFAULT 0.0200,
    gap_max_modifier DECIMAL(8,4) NOT NULL DEFAULT 0.5000,
    anti_trading_enabled TINYINT(1) NOT NULL DEFAULT 1,
    anti_trading_window_hours INT NOT NULL DEFAULT 48,
    anti_trading_allowed_recent_matches INT NOT NULL DEFAULT 2,
    dodge_enabled TINYINT(1) NOT NULL DEFAULT 1,
    dodge_disconnect_grace_seconds INT NOT NULL DEFAULT 10,
    dodge_cooldown_minutes INT NOT NULL DEFAULT 5,
    dodge_apply_in_draft_only TINYINT(1) NOT NULL DEFAULT 1,
    dodge_reject_reset_during_draft TINYINT(1) NOT NULL DEFAULT 1,
    season_scheduler_enabled TINYINT(1) NOT NULL DEFAULT 0,
    season_soft_reset_months VARCHAR(32) NOT NULL DEFAULT '02,04,08,10',
    season_hard_reset_months VARCHAR(32) NOT NULL DEFAULT '06,12',
    season_hard_priority_over_soft TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    updated_by VARCHAR(255) NULL,
    PRIMARY KEY (id)
);

INSERT INTO ban_pick_rating_config (
    id,
    initial_rating,
    base_win_delta,
    base_loss_delta,
    min_rating,
    macro_enabled,
    macro_active_window_days,
    macro_balance_rating,
    macro_active_top_percent,
    macro_rating_step,
    macro_win_adjustment_per_step,
    macro_min_win_delta,
    macro_minimum_active_players,
    gap_enabled,
    gap_rating_diff_step,
    gap_modifier_per_step,
    gap_max_modifier,
    anti_trading_enabled,
    anti_trading_window_hours,
    anti_trading_allowed_recent_matches,
    dodge_enabled,
    dodge_disconnect_grace_seconds,
    dodge_cooldown_minutes,
    dodge_apply_in_draft_only,
    dodge_reject_reset_during_draft,
    season_scheduler_enabled,
    season_soft_reset_months,
    season_hard_reset_months,
    season_hard_priority_over_soft,
    created_at,
    updated_at,
    updated_by
)
SELECT
    1,
    1000,
    30,
    -20,
    0,
    1,
    30,
    1500,
    50,
    10,
    0.0200,
    20,
    4,
    1,
    10,
    0.0200,
    0.5000,
    1,
    48,
    2,
    1,
    10,
    5,
    1,
    1,
    0,
    '02,04,08,10',
    '06,12',
    1,
    NOW(6),
    NOW(6),
    'SYSTEM_DEFAULT'
WHERE NOT EXISTS (
    SELECT 1
    FROM ban_pick_rating_config
    WHERE id = 1
);

COMMIT;
