-- LEGACY / UNSAFE FOR CURRENT WIKI PHASE 1 SCHEMA.
-- Do not import this file directly. Use sql/seed_heroes_v2.sql instead.
-- This old seed writes the removed `roles` column and does not generate slug.
-- =============================================================
-- SQL Insert mẫu cho bảng heroes (MySQL)
-- Chạy file này để seed dữ liệu tướng vào database.
-- Tên tướng PHẢI khớp chính xác với frontend (case-insensitive).
--
-- Lưu ý: Nếu bảng heroes đã có dữ liệu, bỏ qua file này.
--         Nếu bảng chưa tồn tại, Spring JPA (ddl-auto=update)
--         sẽ tự tạo khi khởi động server.
-- =============================================================

INSERT INTO heroes (name, avatar_url, roles) VALUES
('Toro',      '/images/heroes/Toro.jpg',      'Đỡ đòn'),
('Hayate',    '/images/heroes/Hayate.jpg',    'Xạ thủ'),
('Marja',     '/images/heroes/Marja.jpg',     'Pháp sư'),
('Zata',      '/images/heroes/Zata.jpg',      'Sát thủ'),
('Y''bneth',  '/images/heroes/Y''bneth.jpg',  'Đỡ đòn'),
('Wisp',      '/images/heroes/Wisp.jpg',      'Xạ thủ'),
('Billow',    '/images/heroes/Billow.jpg',    'Sát thủ'),
('Sinestrea', '/images/heroes/Sinestrea.jpg', 'Sát thủ'),
('Lorion',    '/images/heroes/Lorion.jpg',    'Pháp sư'),
('Ryoma',     '/images/heroes/Ryoma.jpg',     'Đấu sĩ'),
('Dolia',     '/images/heroes/Dolia.jpg',     'Trợ thủ'),
('Qi',        '/images/heroes/Qi.jpg',        'Đấu sĩ'),
('Aya',       '/images/heroes/Aya.jpg',       'Trợ thủ'),
('Violet',    '/images/heroes/Violet.jpg',    'Xạ thủ'),
('Yue',       '/images/heroes/Yue.jpg',       'Pháp sư'),
('Volkath',   '/images/heroes/Volkath.jpg',   'Đấu sĩ'),
('Enzo',      '/images/heroes/Enzo.jpg',      'Sát thủ'),
('Murad',     '/images/heroes/Murad.jpg',     'Sát thủ'),
('Gildur',    '/images/heroes/Gildur.jpg',    'Pháp sư'),
('Moren',     '/images/heroes/Moren.jpg',     'Xạ thủ'),
('Florentino','/images/heroes/Florentino.jpg','Đấu sĩ'),
('Aleister',  '/images/heroes/Aleister.jpg',  'Pháp sư'),
('Annette',   '/images/heroes/Annette.jpg',   'Trợ thủ'),
('Zephys',    '/images/heroes/Zephys.jpg',    'Đấu sĩ'),
('Elsu',      '/images/heroes/Elsu.jpg',      'Xạ thủ'),
('Airi',      '/images/heroes/Airi.jpg',      'Đấu sĩ'),
('Nakroth',   '/images/heroes/Nakroth.jpg',   'Sát thủ'),
('Fennik',    '/images/heroes/Fennik.jpg',    'Xạ thủ'),
('Liliana',   '/images/heroes/Liliana.jpg',   'Pháp sư'),
('Tachi',     '/images/heroes/Tachi.jpg',     'Đấu sĩ'),
('Preyta',    '/images/heroes/Preyta.jpg',    'Pháp sư'),
('Taara',     '/images/heroes/Taara.jpg',     'Đỡ đòn'),
('Dyadia',    '/images/heroes/Dyadia.jpg',    'Trợ thủ'),
('Quillen',   '/images/heroes/Quillen.jpg',   'Sát thủ'),
('Capheny',   '/images/heroes/Capheny.jpg',   'Xạ thủ'),
('Iggy',      '/images/heroes/Iggy.jpeg',     'Pháp sư'),
('Veera',     '/images/heroes/Veera.jpg',     'Pháp sư'),
('Stuart',    '/images/heroes/Stuart.jpg',    'Xạ thủ'),
('Keera',     '/images/heroes/Keera.jpg',     'Sát thủ'),
('Skud',      '/images/heroes/Skud.jpg',      'Đấu sĩ'),
('Azzen''Ka', '/images/heroes/Azzen''Ka.jpg', 'Pháp sư'),
('Yena',      '/images/heroes/Yena.jpg',      'Đấu sĩ'),
('Mina',      '/images/heroes/Mina.jpg',      'Đỡ đòn'),
('Tel''Annas','/images/heroes/Tel''Annas.jpg', 'Xạ thủ'),
('Goverra',   '/images/heroes/Goverra.jpg',   'Pháp sư'),
('TeeMee',    '/images/heroes/TeeMee.jpg',    'Trợ thủ'),
('Aoi',       '/images/heroes/Aoi.jpeg',      'Sát thủ'),
('Rourka',    '/images/heroes/Rourke.jpg',    'Đấu sĩ'),
('Bolt Baron','/images/heroes/Bolt Baron.jpg','Đấu sĩ'),
('Rouie',     '/images/heroes/Rouie.jpg',     'Trợ thủ'),
('Eland''orr','/images/heroes/Eland''orr.jpg','Xạ thủ'),
('Lumburr',   '/images/heroes/Lumburr.jpg',   'Trợ thủ'),
('Heino',     '/images/heroes/Heino.jpg',     'Pháp sư'),
('Arthur',    '/images/heroes/Athur.jpg',     'Đấu sĩ'),
('Flowborn (Marksman)', '/images/heroes/Flowborn (ADL).jpg', 'Xạ thủ'),
('Edras',     '/images/heroes/Edras.jpg',     'Đấu sĩ'),
('Grakk',     '/images/heroes/Grakk.png',     'Trợ thủ'),
('Jinna',     '/images/heroes/Jinna.jpg',     'Pháp sư'),
('Mganga',    '/images/heroes/Mganga.jpg',    'Pháp sư'),
('Natalya',   '/images/heroes/Natalya.jpg',   'Pháp sư'),
('Kaine',     '/images/heroes/Kaine.jpg',     'Sát thủ'),
('Omen',      '/images/heroes/Omen.jpg',      'Đấu sĩ'),
('Dirak',     '/images/heroes/Dirak.jpg',     'Pháp sư'),
('Butterfly', '/images/heroes/Butterfly.jpg', 'Sát thủ'),
('Wukong',    '/images/heroes/Ngộ Không.jpg', 'Sát thủ'),
('Diaochan',  '/images/heroes/Điêu Thuyền.jpg','Pháp sư'),
('Xeniel',    '/images/heroes/Xeniel.jpg',    'Đỡ đòn'),
('Zanis',     '/images/heroes/Triệu Vân.jpg', 'Đấu sĩ'),
('Ming',      '/images/heroes/Ming.jpg',      'Trợ thủ'),
('Chaugnar',  '/images/heroes/Chaugnar.jpg',  'Đỡ đòn'),
('Astrid',    '/images/heroes/Astrid.jpg',    'Đấu sĩ'),
('Biron',     '/images/heroes/Biron.jpg',     'Đấu sĩ'),
('Roxie',     '/images/heroes/Roxie.jpg',     'Đỡ đòn'),
('Lauriel',   '/images/heroes/Lauriel.jpg',   'Pháp sư'),
('Thorne',    '/images/heroes/Thorn.jpg',     'Xạ thủ'),
('Zuka',      '/images/heroes/Zuka.jpg',      'Đấu sĩ'),
('Tulen',     '/images/heroes/Tulen.jpg',     'Pháp sư'),
('Valhein',   '/images/heroes/Valhein.jpg',   'Xạ thủ'),
('Zip',       '/images/heroes/Zip.jpg',       'Trợ thủ'),
('Max',       '/images/heroes/Max.jpg',       'Đỡ đòn'),
('Sephera',   '/images/heroes/Sephera.jpg',   'Pháp sư'),
('Maloch',    '/images/heroes/Maloch.jpg',    'Đấu sĩ'),
('Riktor',    '/images/heroes/Richter.jpg',   'Đấu sĩ'),
('Thane',     '/images/heroes/Thane.png',     'Đỡ đòn'),
('Yan',       '/images/heroes/Yan.jpg',       'Đấu sĩ'),
('Yorn',      '/images/heroes/Yorn.jpg',      'Xạ thủ'),
('Slimz',     '/images/heroes/Slimz.png',     'Xạ thủ'),
('Laville',   '/images/heroes/Laville.jpg',   'Xạ thủ'),
('Ignis',     '/images/heroes/Ignis.jpg',     'Pháp sư'),
('Ilumia',    '/images/heroes/Ilumia.jpg',    'Pháp sư'),
('Krizzix',   '/images/heroes/Krizzix.png',   'Trợ thủ'),
('Krixi',     '/images/heroes/Krixi.png',     'Pháp sư'),
('Raz',       '/images/heroes/Raz.jpg',       'Sát thủ'),
('Allain',    '/images/heroes/Allain.jpg',    'Đấu sĩ'),
('Cresht',    '/images/heroes/Cresht.jpg',    'Trợ thủ'),
('Omega',     '/images/heroes/Omega.jpg',     'Đỡ đòn'),
('Kahli',     '/images/heroes/Kahlii.png',    'Pháp sư'),
('Arduin',    '/images/heroes/Arduin.jpg',    'Đỡ đòn'),
('Erin',      '/images/heroes/Erin.jpg',      'Xạ thủ'),
('Kil''Groth','/images/heroes/Kil''Groth.gif','Đấu sĩ'),
('Veres',     '/images/heroes/Veres.jpg',     'Đấu sĩ'),
('Arum',      '/images/heroes/Arum.jpg',      'Trợ thủ'),
('Bijan',     '/images/heroes/Bijan.jpg',     'Đấu sĩ'),
('Bonnie',    '/images/heroes/Bonnie.jpg',    'Pháp sư'),
('Teeri',     '/images/heroes/Teeri.jpg',     'Xạ thủ'),
('Baldum',    '/images/heroes/Baldum.jpg',    'Đỡ đòn'),
('Errol',     '/images/heroes/Errol.jpg',     'Đấu sĩ'),
('Helen',     '/images/heroes/Helen.jpg',     'Trợ thủ'),
('Amily',     '/images/heroes/Amily.jpg',     'Đấu sĩ'),
('Wonder Woman','/images/heroes/Wonder Women.jpg','Đấu sĩ'),
('Kriknak',   '/images/heroes/Kriknak.png',   'Sát thủ'),
('Lindis',    '/images/heroes/Lindis.jpg',    'Xạ thủ'),
('Lu Bu',     '/images/heroes/Lữ Bố.jpg',    'Đấu sĩ'),
('Wiro',      '/images/heroes/Wiro.jpg',      'Đỡ đòn'),
('Zill',      '/images/heroes/Zill.jpg',      'Sát thủ'),
('Charlotte', '/images/heroes/Charlotte.jpg', 'Đấu sĩ'),
('Ata',       '/images/heroes/Ata.jpg',       'Đỡ đòn'),
('Alice',     '/images/heroes/Alice.png',     'Trợ thủ'),
('Dextra',    '/images/heroes/Dextra.jpg',    'Đấu sĩ'),
('Paine',     '/images/heroes/Paine.jpg',     'Sát thủ'),
('Ormarr',    '/images/heroes/Omarr.jpg',     'Đỡ đòn'),
('Bright',    '/images/heroes/Bright.jpg',    'Sát thủ'),
('D''Arcy',   '/images/heroes/D''Arcy.jpg',   'Pháp sư'),
('Celica',    '/images/heroes/Celica.jpg',    'Xạ thủ'),
('The Flash', '/images/heroes/The Flash.jpg', 'Sát thủ'),
('Ishar',     '/images/heroes/Ishar.jpg',     'Pháp sư'),
('Superman',  '/images/heroes/Superman.jpg',  'Đấu sĩ')
ON DUPLICATE KEY UPDATE name = VALUES(name);

-- Kiểm tra dữ liệu đã insert thành công:
-- SELECT id, name, roles FROM heroes ORDER BY name LIMIT 10;
